<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\ArrayParameterType;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260908050359 extends AbstractMigration
{
    private const int BATCH_SIZE = 100;

    public function getDescription(): string
    {
        return 'Insert initial translations';
    }

    public function up(Schema $schema): void
    {
        foreach (array_chunk($this->getTranslations(), self::BATCH_SIZE) as $batch) {
            $values = [];
            $parameters = [];

            foreach ($batch as [$key, $language, $text]) {
                $values[] = '(?, ?, ?)';
                $parameters[] = $key;
                $parameters[] = $language;
                $parameters[] = $text;
            }

            $this->addSql(
                sprintf(
                    'INSERT INTO translations (`key`, language, text) VALUES %s',
                    implode(', ', $values),
                ),
                $parameters,
            );
        }
    }

    public function down(Schema $schema): void
    {
        $keys = array_unique(
            array_map(
                static fn (array $translation): string => $translation[0],
                $this->getTranslations(),
            ),
        );

        foreach (array_chunk($keys, self::BATCH_SIZE) as $batch) {
            $this->addSql(
                'DELETE FROM translations WHERE `key` IN (?)',
                [$batch],
                [ArrayParameterType::STRING],
            );
        }
    }

    /**
     * @return list<array{string, string, string}>
     */
    private function getTranslations(): array
    {
        return [
            ['action', 'cz', 'Akce'],
            ['action', 'en', 'Action'],
            ['active', 'cz', 'Aktivní'],
            ['active', 'en', 'Active'],
            ['add', 'cz', 'Přidat'],
            ['add', 'en', 'Add'],
            ['back', 'cz', 'Zpět'],
            ['back', 'en', 'Back'],
            ['created', 'cz', 'Vytvořeno'],
            ['created', 'en', 'Created'],
            ['default', 'cz', 'výchozí'],
            ['default', 'en', 'default'],
            ['delete', 'cz', 'smazat'],
            ['delete', 'en', 'delete'],
            ['delete.user', 'cz', 'Smazat uživatele'],
            ['delete.user', 'en', 'Delete user'],
            ['deleted', 'cz', 'Smazaný'],
            ['deleted', 'en', 'Deleted'],
            ['e-mail', 'cz', 'E-mail'],
            ['e-mail', 'en', 'E-mail'],
            ['edit', 'cz', 'Upravit'],
            ['edit', 'en', 'Edit'],
            ['full-name', 'cz', 'Celé jméno'],
            ['full-name', 'en', 'Full name'],
            ['key', 'cz', 'Klíč'],
            ['key', 'en', 'Key'],
            ['last-login', 'cz', 'Poslení přihlášení'],
            ['last-login', 'en', 'Last login'],
            ['last-login.short', 'cz', 'Přihlášení'],
            ['last-login.short', 'en', 'Last login'],
            ['lishack-cms', 'cz', 'Lishack CMS CZ'],
//            ['lishack-cms', 'de', 'Lishack CMS DE'],
            ['lishack-cms', 'en', 'Lishack CMS EN'],
            ['name', 'cz', 'Jméno'],
            ['name', 'en', 'Name'],
            ['next', 'cz', 'Další'],
            ['next', 'en', 'Next'],
            ['no', 'cz', 'Ne'],
            ['no', 'en', 'No'],
            ['permissions', 'cz', 'Oprávnění'],
            ['permissions', 'en', 'Permissions'],
            ['previous', 'cz', 'Předchozí'],
            ['previous', 'en', 'Previous'],
            ['save', 'cz', 'Uložit'],
            ['save', 'en', 'Save'],
            ['save.data', 'cz', 'Uložit data'],
            ['save.data', 'en', 'Save data'],
            ['save.translations', 'cz', 'Uložit překlady'],
            ['save.translations', 'en', 'Save translations'],
            ['save.user', 'cz', 'Uložit uživatele'],
            ['save.user', 'en', 'Save user'],
            ['text', 'cz', 'Text'],
            ['text', 'en', 'Text'],
            ['user.role.admin', 'cz', 'Administrátor'],
            ['user.role.admin', 'en', 'Administrator'],
            ['user.role.guest', 'cz', 'Host'],
            ['user.role.guest', 'en', 'Guest'],
            ['user.role.manager', 'cz', 'Moderátor'],
            ['user.role.manager', 'en', 'Manager'],
            ['user.role.redactor', 'cz', 'Redaktor'],
            ['user.role.redactor', 'en', 'Redactor'],
            ['user.role.user', 'cz', 'Uživatel'],
            ['user.role.user', 'en', 'User'],
            ['yes', 'cz', 'Ano'],
            ['yes', 'en', 'Yes'],
            ['editor', 'cz', 'Editor'],
            ['editor', 'en', 'Editor'],
            ['search.key', 'cz', 'Vyhledat klíč'],
            ['search.key', 'en', 'Search key'],
            ['search.translation', 'cz', 'Vyhledat překlad'],
            ['search.translation', 'en', 'Search translation'],
            ['save.config', 'cz', 'Uložit nastavení'],
            ['save.config', 'en', 'Save config'],
            ['category', 'cz', 'Kategorie'],
            ['category', 'en', 'Category'],
            ['value', 'cz', 'Hodnota'],
            ['value', 'en', 'Value'],
            ['app.name', 'cz', 'Název aplikace'],
            ['app.name', 'en', 'Application name'],
            ['site.title', 'cz', 'Titulek webu'],
            ['site.title', 'en', 'Website title'],
            ['default_lang.website', 'cz', 'Výchozí jazyk webu'],
            ['default_lang.website', 'en', 'Default website language'],
            ['default_lang.admin', 'cz', 'Výchozí jazyk administrace'],
            ['default_lang.admin', 'en', 'Default administration language'],
            ['recaptcha.site_key', 'cz', 'reCAPTCHA site key'],
            ['recaptcha.site_key', 'en', 'reCAPTCHA site key'],
            ['recaptcha.secret', 'cz', 'reCAPTCHA secret'],
            ['recaptcha.secret', 'en', 'reCAPTCHA secret'],
            ['pagination.page_items', 'cz', 'Počet položek na stránku'],
            ['pagination.page_items', 'en', 'Items per page'],
            ['pagination.max_pages', 'cz', 'Maximální počet stránek'],
            ['pagination.max_pages', 'en', 'Maximum pages'],
            ['js_inject.head', 'cz', 'JavaScript v <head>'],
            ['js_inject.head', 'en', 'JavaScript in <head>'],
            ['js_inject.body_first', 'cz', 'JavaScript na začátku <body>'],
            ['js_inject.body_first', 'en', 'JavaScript at the start of <body>'],
            ['js_inject.body_last', 'cz', 'JavaScript na konci <body>'],
            ['js_inject.body_last', 'en', 'JavaScript at the end of <body>'],
            ['js_inject.ip_exceptions', 'cz', 'Nespouštět JavaScript pro IP (nebo rozsah IP)'],
            ['js_inject.ip_exceptions', 'en', 'JavaScript exceptions for IPs (or IP range)'],
            ['css_inject', 'cz', 'CSS v <head>'],
            ['css_inject', 'en', 'CSS in <head>'],
            ['robots.txt', 'cz', 'Soubor robots.txt'],
            ['robots.txt', 'en', 'File robots.txt'],
            ['open-graph.title', 'cz', 'Open Graph - výchozí titulek'],
            ['open-graph.title', 'en', 'Open Graph - default title'],
            ['open-graph.description', 'cz', 'Open Graph - výchozí popis'],
            ['open-graph.description', 'en', 'Open Graph - default description'],
            ['open-graph.image', 'cz', 'Open Graph - výchozí obrázek (URL)'],
            ['open-graph.image', 'en', 'Open Graph - default image (URL)'],
            ['seo.title', 'cz', 'Název webu'],
            ['seo.title', 'en', 'Website title'],
            ['seo.description', 'cz', 'Popis webu'],
            ['seo.description', 'en', 'Website description'],
            ['seo.index', 'cz', 'Nastavení indexování (meta robots)'],
            ['seo.index', 'en', 'Index settings (meta robots)'],
            ['open-graph.show-locale', 'cz', 'Zobrazovat <meta property="og:locale" ...> v sekci HEAD'],
            ['open-graph.show-locale', 'en', 'Show <meta property="og:locale" ...> in the HEAD section'],
            ['id', 'cz', 'ID'],
            ['id', 'en', 'ID'],
            ['source-url', 'cz', 'Zdrojová URL'],
            ['source-url', 'en', 'Source URL'],
            ['target-url', 'cz', 'Cílová URL'],
            ['target-url', 'en', 'Target URL'],
            ['http-code', 'cz', 'HTTP kód'],
            ['http-code', 'en', 'HTTP code'],
            ['enabled', 'cz', 'Povoleno'],
            ['enabled', 'en', 'Enabled'],
            ['required-items', 'cz', 'Povinné položky'],
            ['required-items', 'en', 'Required items'],
            ['login-name', 'cz', 'Přihlašovací jméno'],
            ['login-name', 'en', 'Login name'],
            ['active.user', 'cz', 'Aktivní uživatel'],
            ['active.user', 'en', 'Active user'],
            ['deleted.user', 'cz', 'Smazaný uživatel'],
            ['deleted.user', 'en', 'Deleted user'],
            ['password', 'cz', 'Heslo'],
            ['password', 'en', 'Password'],
            ['password.again', 'cz', 'Heslo znovu'],
            ['password.again', 'en', 'Password again'],
            ['password.change', 'cz', 'Změnit heslo'],
            ['password.change', 'en', 'Change password'],
            ['enabled.user', 'cz', 'Povolený uživatel (smí se přihlásit)'],
            ['enabled.user', 'en', 'Enabled user (can log in)'],
            ['create', 'cz', 'Vytvořit'],
            ['create', 'en', 'Create'],
            ['user.enabled-callback.himself', 'cz', 'Uživatel nemůže %s sám sebe.'],
            ['user.enabled-callback.himself', 'en', 'User do not %s himself.'],
            ['user.enabled-callback.admin', 'cz', 'Hlavního administrátora nelze %s přes administraci.'],
            ['user.enabled-callback.same-role', 'cz', 'Nemůžete %s uživatele, který má stejné (nebo vyšší) oprávnění jako Vy.'],
            ['user.enabled-callback.update-failed', 'cz', 'Vybraného uživatele se nepodařilo %s.'],
            ['enable', 'cz', 'povolit'],
            ['enable', 'en', 'enable'],
            ['disable', 'cz', 'zakázat'],
            ['disable', 'en', 'disable'],
            ['user.enabled-callback.admin', 'en', 'The main administrator cannot be %sd through the administration.'],
            ['user.enabled-callback.same-role', 'en', 'You cannot %s a user who has the same (or higher) permissions as you.'],
            ['user.enabled-callback.update-failed', 'en', 'The selected user could not be %sd.'],
            ['restore', 'cz', 'obnovit'],
            ['restore', 'en', 'restore'],
            ['user.deleted-callback.himself', 'cz', 'Uživatel nemůže %s sám sebe.'],
            ['user.deleted-callback.himself', 'en', 'User do not %s himself.'],
            ['user.deleted-callback.admin', 'cz', 'Hlavního administrátora nelze %s přes administraci.'],
            ['user.deleted-callback.admin', 'en', 'The main administrator cannot be %sd through the administration.'],
            ['user.deleted-callback.same-role', 'cz', 'Nemůžete %s uživatele, který má stejné (nebo vyšší) oprávnění jako Vy.'],
            ['user.deleted-callback.same-role', 'en', 'You cannot %s a user who has the same (or higher) permissions as you.'],
            ['user.deleted-callback.update-failed', 'cz', 'Vybraného uživatele se nepodařilo %s.'],
            ['user.deleted-callback.update-failed', 'en', 'The selected user could not be %sd.'],
            ['user.role-callback.himself', 'cz', 'Uživatel nemůže měnit vlastní oprávnění.'],
            ['user.role-callback.admin', 'cz', 'Oprávnění hlavního administrátora nelze měnit.'],
            ['user.role-callback.same-role', 'cz', 'Nemůžete měnit oprávnění uživatele, který má stejné (nebo vyšší) oprávnění jako Vy.'],
            ['user.role-callback.role-elevation', 'cz', 'Uživateli nelze udělit stejné, ani vyšší oprávnění, než jaké máte Vy.'],
            ['user.role-callback.update-failed', 'cz', 'U vybraného uživatele se nepodařilo změnit oprávnění.'],
            ['user.role-callback.himself', 'en', 'A user cannot change their own permissions.'],
            ['user.role-callback.admin', 'en', "The main administrator's permissions cannot be changed."],
            ['user.role-callback.same-role', 'en', 'You cannot change the permissions of a user who has the same (or higher) permissions as you.'],
            ['user.role-callback.role-elevation', 'en', 'You cannot grant the same or higher permissions than you have.'],
            ['user.role-callback.update-failed', 'en', 'Permissions could not be changed for the selected user.'],
            ['error', 'cz', 'Chyba'],
            ['error', 'en', 'Error'],
            ['error.form.empty-data', 'cz', 'Formulář odeslal prázdná data.'],
            ['error.form.empty-data', 'en', 'Form sent empty data.'],
            ['error.form.empty-target-lang', 'cz', 'Formulář neodeslal hodnotu cílového jazyka.'],
            ['error.form.empty-target-lang', 'en', 'The form did not submit a target language value.'],
            ['success.form.translations-saved', 'cz', 'Překlady byly uloženy.'],
            ['success.form.translations-saved', 'en', 'The translations have been saved.'],
            ['error.form.missing-required', 'cz', "Povinné pole '%s' je prázdné. Formulář nebyl uložen."],
            ['error.form.missing-required', 'en', "Required field '%s' is empty. Form was not saved."],
            ['error.form.missing-required.settings', 'cz', "Povinná položka nastavení '%s' je prázdná. Nastavení nebylo uloženo."],
            ['error.form.missing-required.settings', 'en', "The required setting item '%s' is empty. The settings was not saved."],
            ['success.form.settings-saved', 'cz', 'Nastavení bylo uloženo.'],
            ['success.form.settings-saved', 'en', 'The settings has been saved.'],
            ['error.form.redirect.invalid-http-code', 'cz', "Neplatný HTTP code '%s'. Nastavení přesměrování nebylo uloženo."],
            ['error.form.redirect.invalid-http-code', 'en', "Invalid HTTP code '%s'. Redirect settings was not saved."],
            ['error.form.unknown-origin', 'cz', 'Neznámý typ formuláře.'],
            ['error.form.unknown-origin', 'en', 'Unknown form type.'],
            ['success.form.redirect-created', 'cz', 'Přesměrování bylo vytvořeno.'],
            ['success.form.redirect-created', 'en', 'The redirect has been created.'],
            ['success.form.redirect-saved', 'cz', 'Změny v přesměrování byly uloženy.'],
            ['success.form.redirect-saved', 'en', 'The redirection changes have been saved.'],
            ['close', 'cz', 'Zavřít'],
            ['close', 'en', 'Close'],
            ['cancel', 'cz', 'Zrušit'],
            ['cancel', 'en', 'Cancel'],
            ['btn.delete', 'cz', 'Smazat'],
            ['btn.delete', 'en', 'Delete'],
            ['modal.title.confirm-delete', 'cz', 'Potvrďte smazání'],
            ['modal.title.confirm-delete', 'en', 'Confirm deletion'],
            ['modal.body.delete-item', 'cz', 'Opravdu chcete položku <strong>%s</strong> smazat?'],
            ['modal.body.delete-item', 'en', 'Are you sure you want to delete <strong>%s</strong>?'],
            ['modal.body.delete-redirect', 'cz', 'Opravdu chcete přesměrování <strong>%s</strong> smazat?'],
            ['modal.body.delete-redirect', 'en', 'Are you sure you want to delete the redirect <strong>%s</strong>?'],
            ['modal.body.delete-translation', 'cz', 'Opravdu chcete překlad <strong>%s</strong> smazat?'],
            ['modal.body.delete-user', 'cz', 'Opravdu chcete uživatele <strong>%s</strong> smazat?'],
            ['modal.body.delete-menu', 'cz', 'Opravdu chcete menu <strong>%s</strong> smazat?'],
            ['modal.body.delete-translation', 'en', 'Are you sure you want to delete the translation <strong>%s</strong>?'],
            ['modal.body.delete-user', 'en', 'Are you sure you want to delete the user <strong>%s</strong>?'],
            ['modal.body.delete-menu', 'en', 'Are you sure you want to delete the menu <strong>%s</strong>?'],
            ['success.form.translation-created', 'cz', 'Překlad byl vytvořen.'],
            ['success.form.translation-created', 'en', 'The translation has been created.'],
            ['success.form.translation-saved', 'cz', 'Překlad byl uložen.'],
            ['success.form.translation-saved', 'en', 'The translation has been saved.'],
            ['success.form.translation-created.named', 'cz', 'Překlad pro <strong>%s</strong> byl vytvořen.'],
            ['success.form.translation-created.named', 'en', 'Translation for <strong>%s</strong> has been created.'],
            ['error.form.translation-create', 'cz', 'Překlad se nepodařilo vytvořit.'],
            ['error.form.translation-create', 'en', 'The translation could not be created.'],
            ['error.form.translation-duplicate-key', 'cz', 'Překlad pro <strong>%s</strong> již existuje. Přejmenujte klíč, nebo upravte stávající %s'],
            ['error.form.translation-duplicate-key', 'en', 'A translation for <strong>%s</strong> already exists. Rename the key or edit the existing %s'],
            ['btn.login', 'cz', 'Přihlásit se'],
            ['btn.login', 'en', 'Log in'],
            ['login.remember', 'cz', 'Zapamatovat přihlášení na 7 dní'],
            ['login.remember', 'en', 'Remember login for 7 days'],
            ['error.form.fill-password', 'cz', 'Vyplňte heslo.'],
            ['error.form.fill-password', 'en', 'Fill in the password.'],
            ['error.form.passwords-not-match', 'cz', 'Hesla se neshodují.'],
            ['error.form.passwords-not-match', 'en', 'The passwords do not match.'],
            ['error.form.user-role-elevation', 'cz', 'Nemůžete udělit stejná nebo vyšší oprávnění, než máte.'],
            ['error.form.user-role-elevation', 'en', 'You cannot grant the same or higher permissions than you have.'],
            ['success.form.user-created', 'cz', 'Uživatel byl vytvořen (ID: %d).'],
            ['success.form.user-created', 'en', 'The user has been created (ID: %d).'],
            ['error.form.no-permissions.user-edit', 'cz', 'Nemáte dostatečná oprávnění pro editaci tohoto uživatele.'],
            ['error.form.no-permissions.user-edit', 'en', 'You do not have sufficient permissions to edit this user.'],
            ['success.form.user-saved', 'cz', 'Uživatel byl uložen.'],
            ['success.form.user-saved', 'en', 'The user has been saved.'],
            ['title.admin.admin.default', 'cz', 'Přehled'],
            ['title.admin.admin.default', 'en', 'Overview'],
            ['title.admin.article.default', 'cz', 'Seznam článků'],
            ['title.admin.article.default', 'en', 'Article list'],
            ['title.admin.article.create', 'cz', 'Vytvoření nového článku'],
            ['title.admin.article.create', 'en', 'Create new article'],
            ['title.admin.article.edit', 'cz', 'Editace článku'],
            ['title.admin.article.edit', 'en', 'Edit article'],
            ['title.admin.config.editor', 'cz', 'Editor nastavení'],
            ['title.admin.config.editor', 'en', 'Configuration editor'],
            ['title.admin.config.website', 'cz', 'Nastavení Website'],
            ['title.admin.config.website', 'en', 'Website settings'],
            ['title.admin.config.seo', 'cz', 'Nastavení SEO'],
            ['title.admin.config.seo', 'en', 'SEO settings'],
            ['title.admin.debug.default', 'cz', 'Ladění'],
            ['title.admin.debug.default', 'en', 'Debug'],
            ['title.admin.email.default', 'cz', 'E-mail'],
            ['title.admin.email.default', 'en', 'E-mail'],
            ['title.admin.menu.default', 'cz', 'Menu'],
            ['title.admin.menu.default', 'en', 'Menu'],
            ['title.admin.menu.create', 'cz', 'Vytvoření menu'],
            ['title.admin.menu.create', 'en', 'Create new menu'],
            ['title.admin.menu.edit', 'cz', 'Editace menu'],
            ['title.admin.menu.edit', 'en', 'Edit menu'],
            ['title.admin.redirect.default', 'cz', 'Přesměrování'],
            ['title.admin.redirect.default', 'en', 'Redirections'],
            ['title.admin.redirect.create', 'cz', 'Vytvořit přesměrování'],
            ['title.admin.redirect.create', 'en', 'Create redirection'],
            ['title.admin.redirect.edit', 'cz', 'Editace přesměrování'],
            ['title.admin.redirect.edit', 'en', 'Edit redirection'],
            ['title.admin.redirect.import', 'cz', 'Import přesměrování'],
            ['title.admin.redirect.import', 'en', 'Import redirections'],
            ['title.admin.redirect.export', 'cz', 'Export přesměrování'],
            ['title.admin.redirect.export', 'en', 'Export redirections'],
            ['title.admin.sign.in', 'cz', 'Admin Login CZ'],
            ['title.admin.sign.in', 'en', 'Admin Login EN'],
            ['title.admin.translation.default', 'cz', 'Lokalizace'],
            ['title.admin.translation.editor', 'cz', 'Editor Lokalizace'],
            ['title.admin.translation.create', 'cz', 'Nový překlad'],
            ['title.admin.translation.edit', 'cz', 'Editace překladu'],
            ['title.admin.translation.default', 'en', 'Localization'],
            ['title.admin.translation.editor', 'en', 'Localization Editor'],
            ['title.admin.translation.create', 'en', 'Create new translation'],
            ['title.admin.translation.edit', 'en', 'Edit translation'],
            ['title.admin.user.default', 'cz', 'Uživatelské účty'],
            ['title.admin.user.create', 'cz', 'Vytvoření nového uživatele'],
            ['title.admin.user.edit', 'cz', 'Editace uživatele'],
            ['title.admin.user.default', 'en', 'User accounts'],
            ['title.admin.user.create', 'en', 'Create new user'],
            ['title.admin.user.edit', 'en', 'Edit user'],
            ['admin.sidebar.main', 'cz', 'Správa webu'],
            ['admin.sidebar.main', 'en', 'Website management'],
            ['admin.sidebar.main.overview', 'cz', 'Přehled'],
            ['admin.sidebar.main.overview', 'en', 'Overview'],
            ['admin.sidebar.main.article', 'cz', 'Články'],
            ['admin.sidebar.main.article', 'en', 'Articles'],
            ['admin.sidebar.main.article.list', 'cz', 'Přehled článků'],
            ['admin.sidebar.main.article.list', 'en', 'Article list'],
            ['admin.sidebar.main.article.create', 'cz', 'Nový článek'],
            ['admin.sidebar.main.article.create', 'en', 'New article'],
            ['admin.sidebar.main.menu', 'cz', 'Menu'],
            ['admin.sidebar.main.menu', 'en', 'Menu'],
            ['admin.sidebar.main.menu.list', 'cz', 'Položky menu'],
            ['admin.sidebar.main.menu.list', 'en', 'Menu items'],
            ['admin.sidebar.main.menu.create', 'cz', 'Nové menu'],
            ['admin.sidebar.main.menu.create', 'en', 'New menu'],
            ['admin.sidebar.main.data', 'cz', 'Data'],
            ['admin.sidebar.main.data', 'en', 'Data'],
            ['admin.sidebar.main.config', 'cz', 'Nastavení'],
            ['admin.sidebar.main.config', 'en', 'Configuration'],
            ['admin.sidebar.main.config.users', 'cz', 'Uživatelské účty'],
            ['admin.sidebar.main.config.users', 'en', 'User accounts'],
            ['admin.sidebar.main.config.localization', 'cz', 'Lokalizace'],
            ['admin.sidebar.main.config.localization', 'en', 'Localization'],
            ['admin.sidebar.main.config.email', 'cz', 'E-mail'],
            ['admin.sidebar.main.config.email', 'en', 'E-mail'],
            ['admin.sidebar.main.config.website', 'cz', 'Website'],
            ['admin.sidebar.main.config.website', 'en', 'Website'],
            ['admin.sidebar.main.config.seo', 'cz', 'SEO'],
            ['admin.sidebar.main.config.seo', 'en', 'SEO'],
            ['admin.sidebar.main.config.editor', 'cz', 'Editor nastavení'],
            ['admin.sidebar.main.config.editor', 'en', 'Config editor'],
            ['admin.sidebar.main.config.redirect', 'cz', 'Přesměrování'],
            ['admin.sidebar.main.config.redirect', 'en', 'Redirections'],
            ['admin.sidebar.main.config.debug', 'cz', 'Ladění'],
            ['admin.sidebar.main.config.debug', 'en', 'Debug'],
            ['admin.sidebar.tools', 'cz', 'Nástroje webu'],
            ['admin.sidebar.tools', 'en', 'Website tools'],
            ['admin.sidebar.tools.goto-website', 'cz', 'Přejít na web'],
            ['admin.sidebar.tools.goto-website', 'en', 'Go to website'],
            ['admin.sidebar.user', 'cz', 'Uživatel <strong class="text-warning">%s</strong>'],
            ['admin.sidebar.user', 'en', 'User <strong class="text-warning">%s</strong>'],
            ['admin.sidebar.user.profile', 'cz', 'Můj profil'],
            ['admin.sidebar.user.profile', 'en', 'My profile'],
            ['admin.sidebar.user.signout', 'cz', 'Odhlášení'],
            ['admin.sidebar.user.signout', 'en', 'Sign out'],
            ['menu-order', 'cz', 'Řazení menu'],
            ['menu-order', 'en', 'Menu order'],
            ['import', 'cz', 'Import'],
            ['import', 'en', 'Import'],
            ['export', 'cz', 'Export'],
            ['export', 'en', 'Export'],
            ['application', 'cz', 'Aplikace'],
            ['application', 'en', 'Application'],
            ['language', 'cz', 'Jazyk'],
            ['language', 'en', 'Language'],
            ['pagination', 'cz', 'Stránkování'],
            ['pagination', 'en', 'Pagination'],
            ['form.article.title', 'cz', 'Název stránky'],
            ['form.article.title', 'en', 'Article title'],
            ['form.article.name_url', 'cz', 'Jméno v URL'],
            ['form.article.name_url', 'en', 'Name URL'],
            ['form.article.published', 'cz', 'Publikováno'],
            ['form.article.published', 'en', 'Published'],
            ['form.article.published_at', 'cz', 'Datum publikace'],
            ['form.article.published_at', 'en', 'Date of publication'],
            ['form.article.updated_at', 'cz', 'Datum editace'],
            ['form.article.updated_at', 'en', 'Last update date'],
            ['form.article.robots', 'cz', 'Nastavení indexování'],
            ['form.article.robots', 'en', 'Indexing'],
            ['form.article.canonical_url', 'cz', 'Cannonical URL'],
            ['form.article.canonical_url', 'en', 'Cannonical URL'],
            ['form.article.og_title', 'cz', 'og:title'],
            ['form.article.og_title', 'en', 'og:title'],
            ['form.article.og_description', 'cz', 'og:description'],
            ['form.article.og_description', 'en', 'og:description'],
            ['form.article.og_image', 'cz', 'og:image'],
            ['form.article.og_image', 'en', 'og:image'],
            ['form.article.og_url', 'cz', 'og:url'],
            ['form.article.og_url', 'en', 'og:url'],
            ['form.article.og_type', 'cz', 'og:type'],
            ['form.article.og_type', 'en', 'og:type'],
            ['form.article.meta_title', 'cz', 'meta title'],
            ['form.article.meta_title', 'en', 'meta title'],
            ['form.article.meta_description', 'cz', 'meta description'],
            ['form.article.meta_description', 'en', 'meta description'],
            ['form.article.content', 'cz', 'Obsah článku'],
            ['form.article.content', 'en', 'Article content'],
            ['form.article.save', 'cz', 'Uložit článek'],
            ['form.article.save', 'en', 'Save article'],
            ['form.article.create', 'cz', 'Vytvořit článek'],
            ['form.article.create', 'en', 'Create article'],
            ['form.article.author', 'cz', 'Autor'],
            ['form.article.author', 'en', 'Author'],
            ['author.unknown', 'cz', '(neznámý)'],
            ['author.unknown', 'en', '(unknown)'],
            ['author.anonymous', 'cz', '(anonymní)'],
            ['author.anonymous', 'en', '(anonymous)'],
            ['author.system', 'cz', '(systém)'],
            ['author.system', 'en', '(system)'],
            ['success.form.article-saved', 'cz', 'Článek byl uložen.'],
            ['success.form.article-saved', 'en', 'The article has been saved.'],
            ['success.form.article-created', 'cz', 'Článek byl vytvořen.'],
            ['success.form.article-created', 'en', 'The article has been created.'],
            ['modal.body.delete-article', 'cz', 'Opravdu chcete článek <strong>%s</strong> smazat?'],
            ['modal.body.delete-article', 'en', 'Are you sure you want to delete the article <strong>%s</strong>?'],
            ['form.article.save-copy', 'cz', 'Vytvořit kopii'],
            ['form.article.save-copy', 'en', 'Create copy'],
            ['form.article.category', 'cz', 'Kategorie'],
            ['form.article.category', 'en', 'Category'],
            ['form.category.name', 'cz', 'Název kategorie'],
            ['form.category.name', 'en', 'Category name'],
            ['form.category.name_url', 'cz', 'Jméno v URL'],
            ['form.category.name_url', 'en', 'Name URL'],
            ['form.category.parent_id', 'cz', 'Nadřazená kategorie'],
            ['form.category.parent_id', 'en', 'Parent category'],
            ['form.category.title', 'cz', 'Titulek kategorie'],
            ['form.category.title', 'en', 'Category title'],
            ['form.category.description', 'cz', 'Popisek kategorie'],
            ['form.category.description', 'en', 'Category description'],
            ['form.category.body', 'cz', 'Anotační text'],
            ['form.category.body', 'en', 'Annotation'],
            ['form.category.hidden', 'cz', 'Kategorie je skrytá'],
            ['form.category.hidden', 'en', 'Category is hidden'],
            ['success.form.category-saved', 'cz', 'Kategorie byla uložena.'],
            ['success.form.category-saved', 'en', 'The category has been saved.'],
            ['success.form.category-created', 'cz', 'Kategorie byla vytvořena.'],
            ['success.form.category-created', 'en', 'The category has been created.'],
            ['admin.article.preview', 'cz', 'Náhled článku'],
            ['admin.article.preview', 'en', 'Article preview'],
            ['article.title.preview', 'cz', '(náhled)'],
            ['article.title.preview', 'en', '(preview)'],
            ['article.id.not-found', 'cz', 'Článek ID: %d nebyl nalezen'],
            ['article.id.not-found', 'en', 'Article ID: %d not found'],
            ['search.article', 'cz', 'Vyhledat článek'],
            ['search.article', 'en', 'Search article'],
            ['dataset.title', 'cz', 'Název datasetu'],
            ['dataset.title', 'en', 'Dataset name'],
            ['slug', 'cz', 'Slug'],
            ['slug', 'en', 'Slug'],
            ['component', 'cz', 'Komponenta'],
            ['component', 'en', 'Component'],
            ['presenter', 'cz', 'Presenter'],
            ['presenter', 'en', 'Presenter'],
            ['modal.body.delete-dataset', 'cz', 'Opravdu chcete dataset <strong>%s</strong> (ID: %d) smazat?'],
            ['modal.body.delete-dataset', 'en', 'Are you sure you want dataset <strong>%s</strong> (ID: %d) smazat?'],
            ['dataset.id.not-found', 'cz', 'Dataset ID: %d nebyl nalezen'],
            ['dataset.id.not-found', 'en', 'Dataset ID: %d not found'],
            ['redirect.id.not-found', 'cz', 'Přesměrování ID: %d nebylo nalezeno'],
            ['redirect.id.not-found', 'en', 'Redirection ID: %d not found'],
            ['translation.key.not-found', 'cz', "Překlad pro '%s' nebyl nalezen"],
            ['translation.key.not-found', 'en', "Translation for '%s' does not found"],
            ['title.admin.data.create', 'cz', 'Vytvoření datové položky'],
            ['title.admin.data.create', 'en', 'Create data item'],
            ['title.admin.data.default', 'cz', 'Seznam dat'],
            ['title.admin.data.default', 'en', 'List of data'],
            ['title.admin.data.edit', 'cz', 'Editace datové položky'],
            ['title.admin.data.edit', 'en', 'Edit data item'],
            ['title.admin.dataset.create', 'cz', 'Vytvoření datasetu'],
            ['title.admin.dataset.create', 'en', 'Create dataset'],
            ['title.admin.dataset.default', 'cz', 'Seznam datasetů'],
            ['title.admin.dataset.default', 'en', 'List of datasets'],
            ['title.admin.dataset.edit', 'cz', 'Editace datasetu'],
            ['title.admin.dataset.edit', 'en', 'Edit dataset'],
            ['admin.sidebar.main.config.dataset', 'cz', 'Datasety'],
            ['admin.sidebar.main.config.dataset', 'en', 'Datasets'],
            ['search.dataset', 'cz', 'Vyhledat dataset'],
            ['search.dataset', 'en', 'Search dataset'],
            ['serach.data', 'cz', 'Vyhledat data'],
            ['serach.data', 'en', 'Search data'],
            ['dataset.column.default', 'cz', 'Výchozí'],
            ['dataset.column.default', 'en', 'Default'],
            ['dataset.column.slug', 'cz', 'Slug'],
            ['dataset.column.slug', 'en', 'Slug'],
            ['dataset.column.required', 'cz', 'Povinný'],
            ['dataset.column.required', 'en', 'Required'],
            ['dataset.column.listed', 'cz', 'V seznamu'],
            ['dataset.column.listed', 'en', 'Listed'],
            ['dataset.column.hidden', 'cz', 'Skrytý'],
            ['dataset.column.hidden', 'en', 'Hidden'],
            ['dataset.column.deleted', 'cz', 'Smazaný'],
            ['dataset.column.deleted', 'en', 'Deleted'],
            ['dataset.column', 'cz', 'Sloupce'],
            ['dataset.column', 'en', 'Columns'],
            ['dataset.metadata', 'cz', 'Metadata datasetu'],
            ['dataset.metadata', 'en', 'Dataset metadata'],
            ['dataset.settings', 'cz', 'Nastavení datasetu'],
            ['dataset.settings', 'en', 'Dataset settings'],
            ['dataset.id.not-set', 'cz', 'ID datasetu nebylo nastaveno.'],
            ['dataset.id.not-set', 'en', 'Dataset ID does not set.'],
            ['dataset.item-id.not-found', 'cz', 'Položka datasetu s ID: %d nebyla nalezena.'],
            ['dataset.item-id.not-found', 'en', 'Dataset item with ID: %d not found.'],
            ['dataset.item-id.not-set', 'cz', 'ID položky datasetu nebylo nastaveno.'],
            ['dataset.item-id.not-set', 'en', 'Dataset item ID does not set.'],
            ['dataset.item.not-created', 'cz', 'Položku datasetu se nepodařilo vytvořit.'],
            ['dataset.item.not-created', 'en', 'Unable to create dataset item.'],
            ['dataset.item.created', 'cz', 'Nová položka datasetu byla vytvořena s ID: %d.'],
            ['dataset.item.created', 'en', 'A new dataset item was created with ID: %d.'],
            ['dataset.item.saved', 'cz', 'Položka datové sady s ID: %d byla uložena.'],
            ['dataset.item.saved', 'en', 'Dataset item with ID: %d has been saved.'],
            ['dataset.column.type.html', 'cz', 'HTML'],
            ['dataset.column.type.html', 'en', 'HTML'],
            ['modal.body.delete-dataset-data', 'cz', 'Opravdu chcete řádek ID: <strong>%d</strong> smazat?'],
            ['modal.body.delete-dataset-data', 'en', 'Are you sure you want to delete row ID: <strong>%d</strong>?'],
            ['admin.sidebar.main.dataset.create', 'cz', 'Nový dataset'],
            ['admin.sidebar.main.dataset.create', 'en', 'New dataset'],
            ['dataset.column.name', 'cz', 'Jméno'],
            ['dataset.column.name', 'en', 'Name'],
            ['dataset.column.type', 'cz', 'Typ'],
            ['dataset.column.type', 'en', 'Type'],
            ['dataset.column.type.bool', 'cz', 'BOOL'],
            ['dataset.column.type.bool', 'en', 'BOOL'],
            ['dataset.column.type.int', 'cz', 'INT'],
            ['dataset.column.type.int', 'en', 'INT'],
            ['dataset.column.type.json', 'cz', 'JSON'],
            ['dataset.column.type.json', 'en', 'JSON'],
            ['dataset.column.type.string', 'cz', 'STRING'],
            ['dataset.column.type.string', 'en', 'STRING'],
            ['dataset.column.type.text', 'cz', 'TEXT'],
            ['dataset.column.type.text', 'en', 'TEXT'],
            ['dataset.column.type.wysiwyg', 'cz', 'WYSIWYG'],
            ['dataset.column.type.wysiwyg', 'en', 'WYSIWYG'],
            ['title.admin.fileexplorer.default', 'cz', 'Správce souborů'],
            ['title.admin.fileexplorer.default', 'en', 'File explorer'],
            ['title.admin.gallery.default', 'cz', 'Fotogalerie'],
            ['title.admin.gallery.default', 'en', 'Gallery'],
            ['upload', 'cz', 'Nahrát'],
            ['upload', 'en', 'Upload'],
            ['title.admin.fileexplorer.upload', 'cz', 'Nahrávání souboru'],
            ['title.admin.fileexplorer.upload', 'en', 'File upload'],
        ];
    }
}
